### PR TITLE
Root apex domain

### PR DESCRIPTION
**Pull request by peter-poki**
Add ability to use root apex domain as main domain (without subdomain -> without creating subdomain dns zone)

### CODE REVIEW

**Review by tomhobson — CHANGES_REQUESTED** [review]
```
resource "azurerm_role_assignment" "Give_ExternalDNS_SP_Contributor_Access_to_ResourceGroup" {
```

Do you have to switch this one too if subdomain is not going to be created?

**Comment by peter-poki** [comment]
Hi Tom, there is already count on the original one, that takes into account nonempty subdomain, see https://github.com/jenkins-x-terraform/terraform-jx-azure/blob/main/terraform-jx-azuredns/main.tf#L31

**Comment by tomhobson** [comment]
We probably shouldn't give permissions where we don't need them, also should we be creating the resource group if we don't need that?

It's probably best to create as little resources as possible.

**Comment by peter-poki** [comment]
Closing PR will open a new one in second, I messed up

**Pull request closed without merging**
