### PR TITLE
feat: add cluster nodes rsg client ID to jx-requirements

### PR DESCRIPTION
**Pull request by Skisocks**
Populates the cluster nodes resource group client ID added [here](https://github.com/jenkins-x/jx-api/pull/183)

https://github.com/jenkins-x/jx/issues/8580

### CODE REVIEW

**Comment by msvticket** [comment]
I'd say @tomhobson is better suited than me when it comes to reviewing something azure specific.

/cc tomhobson

**Review by tomhobson — APPROVED** [review]

**Comment by Skisocks** [comment]
@tomhobson can I get an okay-to-test? :smile:

**Pull request merged**
